language:
  - node_js
node_js:
  - '12'
stages:
  - test
script:
  - npm ci
  - npm install
  - npm install --save-dev@types/jest @types/node jest ts-jest typescript
  - npm install --save-dev jest
  - npm i @types/jest
  - npm test
